### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci-pp4-charity-event-orginizer#2]
Epic: #1 

## User Story:
As a **user** I can **sign in** so that **I can use all of the website features**.

## Tasks:

- [ ] Install and set up authentication package
- [ ] Create view/template/url
- [ ] Configure navigation links

## Acceptance Criteria:
- Existing User should be redirected to home page
- Non existing user should be informed
- Signing in should display user only features
