### ISSUE TITLE
USER STORY: Create event

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci-pp4-charity-event-orginizer#6]
Epic: #5 

## User Story:
As a **event organizer user** I can **create a new event** so that **I can display and promote my event for interested users**.

## Tasks:

- [ ] Create event model
- [ ] Create template with form for creating the event
- [ ] Create view for displaying the form and submitting the event

## Acceptance Criteria:
- Submitting an event should populate the database with the new event
- New events should be added as not approved
- User should be informed that successfully submitted form is awaiting approval
- Redirected to the user's event list
