### ISSUE TITLE
USER STORY: EDIT EVENT

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci-pp4-charity-event-orginizer#7]
Epic: #5 

## User Story:
As a **event organizer user** I can **edit events I have created** so that **I can fix or amend information regarding my event**.

## Tasks:

- [ ] Create template with editing form with prepopulated information
- [ ] Create view for displaying and submitting form
- [ ] Successfully submmiting the form should redirect to the user's event list

## Acceptance Criteria:
- Successfully editing a form should reset its status to not approved
- Database should be updated with new information

**Comment by felipesandoli** [comment]
For now updating the event takes the user to the homepage, will be updated once the my events page has been set up
