### ISSUE TITLE
USER STORY: Event navigation

### ISSUE THREAD

**Issue by felipesandoli** [felipesandoli/ci-pp4-charity-event-orginizer#9]
Epic: #8 

## User Story:
As a **user** I can **View an event list based on my location** so that **See what events are happening close to me**.

## Tasks:

- [ ] Create home page with list of events and navigation links
- [ ] Create page with events created by the user and events that user will participate or have participated
- [ ] Create page that displays full details of the event clicked by the user

## Acceptance Criteria:
- The events on home page and user's events should display a brief summary of the event
- Clicking on the event redirects the user to the event page where all information can be found
- User interaction should be limited if user is not authenticated
